### ISSUE TITLE
Feta repos du har bror 

### ISSUE THREAD

**Issue by VictorWinberg** [antonidag/Gyro#1]
{{vad titeln säger}}

**Comment by antonidag** [comment]
?
--
Skickat från appen myMail för Android söndag, 29 november 2015, 08:47em +01:00 från Victor Winberg < notifications@github.com> :

**Comment by VictorWinberg** [comment]
Jag blev fett imponerad på dina tomma repos 😋

**Comment by antonidag** [comment]
Jaha, dom är lite buggade 
--
Skickat från appen myMail för Android söndag, 29 november 2015, 08:47em +01:00 från Victor Winberg < notifications@github.com> :

**Comment by VictorWinberg** [comment]
Debug.discard(bug);

**Comment by VictorWinberg** [comment]
Ser bra ut.
